version: '3.8'
services:
  mitemp:
    image: mitempprojekt/mitemp
    container_name: mitemp
    network_mode: host
    volumes:
      - '/home/pi/mitemp/sensors.ini:/app/sensors.ini'
      - '/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket'
    privileged: true
    restart: unless-stopped

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - '9091:9091'
    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - '/home/pi/mitemp/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    restart: unless-stopped
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/mitemp.json
    volumes:
      - '/home/pi/mitemp/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml'
      - '/home/pi/mitemp/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml'
      - '/home/pi/mitemp/dashboards:/var/lib/grafana/dashboards'
      - '/home/pi/mitemp/pushover.yaml:/etc/grafana/provisioning/notifiers/pushover.yaml'
      - 'home/pi/mitemp/alerts.yaml:/etc/grafana/provisioning/rules/alerts.yaml'
