{
 "title": "Sensor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "label_values(sensor_temperature_celsius, sensor)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sensor_temperature_celsius{sensor=\"$sensor\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Luftfeuchtigkeit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sensor_humidity_percent{sensor=\"$sensor\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Batteriespannung",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "expr": "sensor_battery_raw{sensor=\"$sensor\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Aktuelle Temperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_temperature_celsius{sensor=\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aktuelle Batteriespannung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_battery_raw{sensor=\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Aktuelle Luftfeuchtigkeit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_humidity_percent{sensor=\"$sensor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}